### ISSUE TITLE
Boolean literals.

### ISSUE THREAD

**Issue by andrey-nikanorov** [jlkiri/tsx-ray#2]
Hi!
I used this lib in my project. And I have issue with providing boolean literals in interfaces.
`interface SomeInterface { someKey: true, anotherKey: false }`
I want to contribute this repo. Could u pls open the access to push branches and creating PR?

**Comment by jlkiri** [comment]
Available in `0.1.7`.

Btw, I just noticed that documentation is wrong. To parse a file at some path you need to import a `extractInterfacesFromFile` function and not `extractInterfaces`. I'll fix it.
